---
- name: Zabbix | Create /etc/zabbix/scripts directory
    file:
      path: /etc/zabbix/scripts
      owner: root
      group: root
      state: directory
      mode: 0755
    become: yes

- name: Zabbix | Add disocvery script
  copy:
    src: diskMountMonitor.sh
    dest: /etc/zabbix/scripts/
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Zabbix | setup item keys
  blockinfile:
    path: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    block: |
      UserParameter=mount.fs.scan[*],/etc/zabbix/scripts/MountMonitor.sh scan
      UserParameter=mount.fs.ismounted[*],/etc/zabbix/scripts/MountMonitor.sh isMountpointMounted $2
  notify:
    - "Zabbix | Restart agent"
  become: yes