---
# tasks file for zabbix-agent

- name: Zabbix | install zabbix repo
  yum:
    name: "https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm"
    state: present
  become: yes

- name: Zabbix | install zabbix-agent
  yum:
    name: zabbix-agent
    state: latest
  become: yes

- name: Zabbix | Copy agent config
  template:
    src: zabbix_agentd.j2
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644
  become: yes

#- name: Zabbix | open zabbix agent port
#  firewalld:
#    port: 10050/tcp
#    permanent: yes
#    state: enabled
#  become: yes

- name: Zabbix | open zabbix agent port
  shell: |
    firewall-cmd --zone=public --permanent --add-port=10050/tcp 
    firewall-cmd --reload
  become: yes 

- name: Zabbix | Start zabbix agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes
  become: yes
